USE doudou;
DROP TABLE IF EXISTS Child;
CREATE TABLE Child
(
	id				 	 INT UNSIGNED NOT NULL AUTO_INCREMENT, 
    firstName			 VARCHAR(20) NOT NULL DEFAULT '',
    lastName			 VARCHAR(20) NOT NULL DEFAULT '',
    gender				 VARCHAR(10) NOT NULL DEFAULT 'Male',
    birthDate			 DATE DEFAULT '0000-00-00' NOT NULL ,
    description			 VARCHAR(255) NOT NULL DEFAULT '',
    photoURL   			 VARCHAR(255) NOT NULL DEFAULT '',
    cover				 VARCHAR(255) NOT NULL DEFAULT '',
    
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
