USE doudou;
DROP TABLE IF EXISTS ChildClass;
CREATE TABLE ChildClass
(
	id				 	INT UNSIGNED NOT NULL AUTO_INCREMENT,
    childId     		INT UNSIGNED NOT NULL DEFAULT 0,
    classId				INT UNSIGNED NOT NULL DEFAULT 0,
    startTime			DATE DEFAULT '0000-00-00' NOT NULL ,
    endTime				DATE DEFAULT '0000-00-00' NOT NULL ,
    available			BOOL NOT NULL DEFAULT TRUE,
    
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
